### ISSUE TITLE
[RFE] Individual environment config files

### ISSUE THREAD

**Issue by mskarbek** [davmac314/dinit#10]
It would be nice to be able to create a file with environment variables for each service. Even better when that file could be created by another service (as a dependency) and loaded during the execution of a particular service.

**Comment by davmac314** [comment]
Yes, I've been thinking about per-service environment.

For this:
> that file could be created by another service (as a dependency) and loaded during the execution of a particular service.

would it be suitable to add a `dinitctl` command/option to re-load the environment for a service? Then if you have a shell script that builds up the environment file it just needs to issue a command to load it for the other service.

**Comment by mskarbek** [comment]
Reloading `dinit` with the command will be sufficient.

**Comment by davmac314** [comment]
Finally implemented, in the 0.6.0 release. Use `env-file` service parameter to specify a file to read environment from; the file is read whenever the service process is started/restarted.
