### ISSUE TITLE
Let's talk about "Externally triggered services"

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#103]
Hi.
I thought about it. This makes the state of services more dynamic.  not just between "STARTED" and "STOPPED". It looks good, but I have a question:
1- What is its use? I still can't understand what Trigger is needed. Thank you for explaining more about it :)
Currently this is the closest thing I found is `udev-trigger`. The command `/bin/udevadm trigger --action=add` represent all nodes that were previously in `/dev` to `udev`.

I want to implement trigger services as follows:
An optional command: `early-command` This command is used when the service starts and must be exited with return code 0. After closing the `early-command`, the trigger is ready.
`early-command` should always exit with return code 0. If it needs to be always running, it should be defined as depends. That is, `early-command` is sensitive to depends. i mean if `depends-on = udev` exists, `early-command` will not be executed until its prerequisite is met. This allows a trigger service to set its early-command on a daemon using depends.

A Required command: `command` This command happens after trigger. I don't think I need to explain more about it.

Finally, I will show my implementation with two examples:
````
type = need-trigger # Thats example
early-command = Prepare gun; reload them & aim to the head
command = Shoot the target
````
Real example:
````
type = need-trigger
command = /bin/udevadm trigger --action=add`

depends-on = udevd
````
regards

**Comment by davmac314** [comment]
Nothing to do with udev-trigger really: it means that a service state is set to started by some other event happening. For example, you want a network service started only after some network device becomes available; you model the service as having a dependency (`network-dev-eth0` for example) and then you arrange that when the device is available that the service is triggered (maybe via a dinitctl command, eg `dinitctl trigger network-dev-eth0`).

In many cases you could probably accomplish the same thing via having `network-dev-eth0` be a scripted service which waits until the condition is met, but that requires running actual processes (This would be more like what I think you are trying to show in your example. But I don't think there's a point in having a separate service type for this; just have two services where one depends on the other). However, it doesn't require any processes to run.

**Comment by mobin-2008** [comment]
Ok; thanks for explain it. I think about it.

**Comment by mobin-2008** [comment]
I think about your example & understand it: you create a service (call it `network-eth0`) & set it as folows:
````
type = need-trigger # Thats example type. I think we dont need another type.
command = Create required nodes on /dev & everything need to use system's eth0 network
trigger-command = Connect to it when you mount LAN cable
````
You create everything needed to connect to eth0 when start `network-eth0`; you wait to access to LAN cable; when you mounted that; run `trigger-command` via `dinitctl trigger network-eth0` for connecting to the network.

Another example:
````
type = scripted #Without new type; i like it
command = swapon -a
trigger-command = swapon -a
stop-command = swapoff -a

depends-on = root-rw
````
call it `swap`. its service enable all swap file/prations at start time but when we need to add another swap instead of restarting them; use trigger command. i know you can enable swaps manally but thats example.

I change implement trigger as follows:
`trigger-command`: This command runned when service is triggered. thats simple and can be used with all services types (Not on `internal` thats expected).
Lets talk about when service is triggered: i like add a new command such as `dinitctl trigger` to `dinitctl`. meanwhile have a command to services can trigger another services (E.g `trigger-service = example_service`) looks good but thats need to revised.

**Comment by Duncaen** [comment]
```
type = scripted
command = mount -t nfs 192.168.0.123:/data /data
depends = network-dev-eth0
```

When network goes up you run `dinitctl trigger network-dev-eth0`  from i.e. NetworkManager hooks.


`network-dev-eth0` would be like a internal service, that is considered up when its "triggered" by the external program.

**Comment by davmac314** [comment]
Can we close this issue?

**Comment by mobin-2008** [comment]
Yes. I'm not worried about this for now.
