### ISSUE TITLE
Typos in the comparison doc file

### ISSUE THREAD

**Issue by Elcoid** [davmac314/dinit#104]
Hello, I found some typos in the comparison doc file. Here is the patch to fix them. By the way, I find it's a nicely written and comprehensive file!

    113c113
    < to be real problems. It may also make it much more difficult to see what will else will start
    ---
    > to be real problems. It may also make it much more difficult to see what else will start
    142c142
    < be used (via the "nosh" interpreter) to implement service commands without requiring the user of a
    ---
    > be used (via the "nosh" interpreter) to implement service commands without requiring the use of a
    178c178
    < metatdata extracted from the service scripts is cached in an alternative format).
    ---
    > metadata extracted from the service scripts is cached in an alternative format).
    188c188
    < database. Services are are configured via a directory structure, with a
    ---
    > database. Services are configured via a directory structure, with a
    217c217
    < It appears that S6-RC supports only hard dependencies: that is if, a service depends
    ---
    > It appears that S6-RC supports only hard dependencies: that is, if a service depends

**Comment by davmac314** [comment]
Fixes applied in 9ba4ceaea04e8e6aa04c0bb75034da4e675f9ddf, thanks for reporting them!
