### ISSUE TITLE
improve service environment variables

### ISSUE THREAD

**Issue by Duncaen** [davmac314/dinit#109]
Here are a few features I would like to see regarding environment variables, and I would be open to contribute them, but would like to have some feedback before I would work on them.

## streamlined environment handling

I think it would be nice if variables from `env-file` in the command line and and when resolving `socket-listen`, `logfile`, `working-dir` and `pid-file`, instead of just the `dinit` processes environment.

Two alternative approaches for loading `env-file`
1. when the service is loaded
2. when the service starts, and then resolve paths and the command line.

I would prefer 1. as this would allow linting with `dinitcheck` and would open the door for a `dinitctl` command to inspect and set per service variables:

```
dinitctl setenv [--service <service name>] [name[=value] ...]
dinitctl getenv [--service <service name>] [name ...]
```

## default user variables

Additionally I think there are a few variables that should be initialized by default based on the `run-as` users `/etc/passwd` entry:
* `HOME`
* `LOGNAME`
* `SHELL`

I think those should be set before loading `env-file`, so that `env-file` could reference the right `HOME`.
The `env-file` could then unset or overwrite those default variables if required.

## basic substitutions

Another feature I think would be nice to have is basic posix shell variable substitutions in settings and in the `env-file`.

The ones I think are the most useful:
```
${VAR-value if var is unset or null}
${VAR+alternative value if var is set}
```

Checking that a variable is set might be useful, but is not super important:
```
${VAR?[error if var is not set with optional description]}
```

I think `${VAR%...}` and `${VAR#...}` are probably not useful enough to justify the extra requirement for a posix pattern matching implementation.

**Comment by davmac314** [comment]
> Two alternative approaches for loading env-file
> 
> 1.     when the service is loaded
> 2.     when the service starts, and then resolve paths and the command line.
> 
> I would prefer 1. 
> 

Yes, I have been thinking about this for a while and would also prefer 1.

Functionality to set environment variables for specific services is also something I've been thinking about, so no objections there either.

> default user variables

I have no objection to any of these.

> basic substitutions

I am hesitant because the question soon becomes "where do you draw the line". However for the two that you highlight (`${VAR-...}` and `${VAR+...}`) I would accept a merge request.

Thanks for checking!

**Comment by dkwo** [comment]
> I think those should be set before loading `env-file`, so that `env-file` could reference the right `HOME`.

Do I understand correctly that this feature is currently not present in dinit?
@davmac314 If so, are you open to someone implementing it?
I think this would help with user services.
