### ISSUE TITLE
[RFE] Redirect stdout/stderr for all services

### ISSUE THREAD

**Issue by mskarbek** [davmac314/dinit#11]
Currently, only one service is able to print to the console, the rest is expected to use some kind of logging management (rsyslog for example). It is perfectly valid and makes sense in a bare metal/VM scenario but falls apart in containers context. It would be very beneficial for containers use case to be able to redirect stdout/stderr of all running services to console and let a container runtime manage the logs.

**Comment by davmac314** [comment]
In recent commit 11c131eef20351d5f6cfaa6bedba3dcb5696cd03 I added a "shares-console" service option which is perhaps the solution here? The other thing you can do is specify the log file as "/dev/tty" which should cause output to go to the "console". Are either of those solutions good enough?

**Comment by mskarbek** [comment]
`shares-console` seems to be what I need. I'll rebuild from `master`, play a little with that and come back with feedback.

**Comment by mobin-2008** [comment]
I mark this issue as `stale` & i wanna close it because created 4 years ago & it seems resolved.

@mskarbek any news?

**Comment by mobin-2008** [comment]
@mskarbek I close it if you need help about it; reopen it.
