### ISSUE TITLE
Example linux services: rootfscheck.sh: Script will broken when btrfs subvolume is used!

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#117]
Hi!
Seems like when btrfs subvolume used for root; `findmnt` return full path of root:
https://github.com/davmac314/dinit/blob/39595191db51e1e2e444bb04ec7c908970e01227/doc/linux/services/rootfscheck.sh#L6
````
❯ findmnt -o SOURCE -n -M /
/dev/sda4[/@rootfs]
````
but `fsck` dont support that!
````
❯ fsck -C -a /dev/sda4/[/@rootfs]
fsck from util-linux 2.38.1
fsck.ext2: Not a directory while trying to open /dev/sda4/[/@rootfs]
/dev/sda4/[/@rootfs]: 
The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

````
@q66 This issue affects chimera linux too.

Possible fixes:
I'm not sure but i think its better than using `findmnt` tool: `eval $(lsblk -oMOUNTPOINT,NAME -P | grep 'MOUNTPOINT="/"'); echo /dev/$NAME`

regards

**Comment by mobin-2008** [comment]
Regression from: https://github.com/davmac314/dinit/commit/27d4e2b83f9955b4cc6e941f589bd4a6db99bcc1

**Comment by davmac314** [comment]
I don't think this is strictly a regression; the reason I changed it in the first place is because fsck cannot always correctly find the device by itself (it relies on /etc/fstab which may be inaccurate).

**Comment by mobin-2008** [comment]
I know about that; But in the past, `rootfscheck.sh` could check btrfs disk by giving `/` to `fsck` (if `fstab` is correct, of course), but the newer solution breaks checking btrfs disks. Its is a regression in my opinion.
