### ISSUE TITLE
[question] iwd + dinit prevent shutdown

### ISSUE THREAD

**Issue by bokunodev** [davmac314/dinit#124]
its tagged as question. but probably a bug.
i have two system, both are artix linux.
one use openrc and another (the one that i use) use dinit.
i've tried iwd on both. but strangely, this only happen with dinit.
when i try to shutdown my system, dinit stuck, just stuck. it ignore any keyboard input (event sysreq). the console also froze, no blinking cursor, no output, no kernel panic message etc.
i can how ever, do **un-graceful shutdown** by using emergency shutdown sysreq.
~
also if i start iwd manually `dinitctl start iwd`, it froze my shell.

**Comment by davmac314** [comment]
Please note I'm not associated with Artix and can provide only limited support on a voluntary basis.

> also if i start iwd manually dinitctl start iwd, it froze my shell.

Let's start with this. What exactly do you mean "froze your shell"? Does ctrl+C return you to the shell prompt? Do other programs continue to run or does your system freeze? Can you also provide more complete information, such as the contents of the `iwd` service script, and any associated log file.

Re the shutdown issue, what is the output of `dinitctl status iwd` just before you try to shtudown?

My suspicion is that iwd is never completing startup.

**Comment by konimex** [comment]
I'm on leave right now but I'll take a look this Saturday to see if this is a problem with how Artix writes the iwd script.

**Comment by mobin-2008** [comment]
Hi @bokunodev. I suggest opening this issue on the Artix's forum (https://forum.artixlinux.org) as it seems to be a bug in Artix's implementation of dinit.
> Please note I'm not associated with Artix and can provide only limited support on a voluntary basis.

&mdash;
About this issue; I reviewed `iwd` dinit script in Artix (https://gitea.artixlinux.org/packagesI/iwd-dinit/src/branch/master/x86_64/community/iwd) and seems dont have any problem:
````
type            = process
command         = /usr/lib/iwd/iwd
smooth-recovery = true
logfile         = /var/log/dinit/iwd.log
depends-on      = udev-settle
depends-on      = dbus
````
Its run `/usr/lib/iwd/iwd` as `process` and `dinit` sending `SIGTERM` at stop process. everything seems ok. @bokunodev Please:

- Check `/var/log/dinit/iwd.log` file.
- Run `/usr/lib/iwd/iwd` normally in terminal and send `SIGTERM` and see what happens.
- Check dinit don't send `SIGKILL` to `iwd` in shutdown process? from dinit-service.5 man-page:
> [stop-timeout = XXX.YYY](https://mobin-2008.github.io/dinit/man-pages-html/dinit-service.5.html#stop~2)
    Specifies the time in seconds allowed for the service to stop. If the service takes longer than this, its process group is sent a SIGKILL signal which should cause it to terminate immediately. The timeout period begins only when all dependent services have already stopped. The default timeout is 10 seconds. Specify a value of 0 to allow unlimited stop time.

Seems like something is broken.
- > Re the shutdown issue, what is the output of dinitctl status iwd just before you try to shtudown?

regards

**Comment by davmac314** [comment]
> dinitctl stop iwd does mark the service as stoped. but the pid is still there pidof iwd

Hmm, that really shouldn't happen. If possible, can you:
- start iwd
- check its pid according to dinit, using `dinitctl status iwd`
- use `pidof iwd` to check it corresponds (and make sure there is only one such process; perhaps there is a secondary process)
- stop it via `dinitctl stop iwd`
- use `pidof iwd` again and see if anything has changed (perhaps there is a secondary process)

As Mobin suggested you can also post in the Artix forums. It would be interesting to know if others are having the same problem (and if anyone else has a solution). However I am happy to continue to try and diagnose the problem here, if you can do the necessary experiments.

(Note that in general the Artix forums are probably a better bet to post for issues that aren't definite dinit bugs. I do monitor those forums as well so will still see and be able to respond if necessary).

**Comment by davmac314** [comment]
Ok, thanks; however the video doesn't show the service marked as stopped - and it seems like it's not stopping, since you're using ^c to break out of `dinitctl stop iwd`, and the second execution of `dinitctl stop iwd` doesn't report the service as already stopped. Given you've said even sending sigkill to the iwd process seems to be ignored, I wonder if something is going wrong at the kernel level. I'm not sure why it works with openrc in that case. Let's see if there's any response to the forum post or if konimex can figure anything out.

(Another thing to check would be `dmesg` output after trying to stop iwd. There might be a clue there.)

**Comment by mobin-2008** [comment]
I test this case with my Artix linux and everything is ok! look at terminal output:
````
➜  ~ sudo dinitctl status iwd
Service: iwd
    State: STARTED
    Activation: start due to dependent(s)
    Process ID: 663
➜  ~ pidof iwd
663
➜  ~ sudo dinitctl stop iwd  
Service 'iwd' stopped.
➜  ~ sudo dinitctl status iwd
Service: iwd
    State: STOPPED
➜  ~ pidof iwd             
➜  ~ echo $?
1
````
System has fully shutdown but the point is my Artix is not up to date! I update my artix and test this case again.

**Comment by mobin-2008** [comment]
I tested that after update my Artix. but everything is ok!
I suggest to use `strace` to see whats happens in `iwd`. Please do following steps:

1. install `strace` package: `sudo pacman -S strace`
2. Run `iwd`
3. See PID of `iwd` (`sudo dinitctl status iwd`) and use `strace` : `sudo strace -p #PID#`
4. Send `sudo dinitctl stop iwd` and see what happens. It's must closed with something like this: `++exited with 0++`.
5. Post **stderr** of `strace`

**Comment by davmac314** [comment]
dmesg output confirms this is a kernel bug:
```
[ 4263.397881] #PF: supervisor read access in kernel mode
[ 4263.397884] #PF: error_code(0x0000) - not-present page
[ 4263.397886] PGD 0 P4D 0 
[ 4263.397890] Oops: 0000 [#1] SMP PTI
[ 4263.397894] CPU: 3 PID: 5567 Comm: iwd Tainted: G           OE     5.15.77-1-lts #1 951f9a81b188084cf7ff3b5505510bc79b616a07
[ 4263.397898] Hardware name: LENOVO 6234E87/LENOVO, BIOS 5CKT77AUS 05/07/2012
[ 4263.397900] RIP: 0010:memcmp+0x2e/0x50
[ 4263.397907] Code: 06 48 39 07 75 17 48 83 c7 08 48 83 c6 08 48 83 ea 08 48 83 fa 07 77 e6 48 85 d2 74 20 31 c9 eb 09 48 83 c1 01 48 39 ca 74 0e <0f> b6 04 0f 44 0f b6 04 0e 44 29 c0 74 e
[ 4263.397910] RSP: 0018:ffffb855c00f76e0 EFLAGS: 00010246
[ 4263.397913] RAX: 0000000000000001 RBX: ffff8ec643742e00 RCX: 0000000000000000
[ 4263.397915] RDX: 0000000000000007 RSI: ffffffffc049d84a RDI: 0000000000000000
[ 4263.397917] RBP: ffffb855c051d000 R08: 0000000020000000 R09: ffff8ec643742e2c
[ 4263.397919] R10: ffff8ec643742e50 R11: 0000000000000108 R12: 0000000000000000
[ 4263.397921] R13: 0000000000000000 R14: 0000000000000000 R15: ffff8ec740d7d448
[ 4263.397924] FS:  00007f3962818740(0000) GS:ffff8ec7c9580000(0000) knlGS:0000000000000000
[ 4263.397926] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 4263.397929] CR2: 0000000000000000 CR3: 00000001262a2000 CR4: 00000000000406e0
[ 4263.397931] Call Trace:
[ 4263.397935]  <TASK>
[ 4263.397937]  rtw_cfg80211_inform_bss+0x7d4/0xe12 [8188eu 0000000000000000000000000000000000000000]
[ 4263.397990]  ? cfg80211_ref_bss+0x88/0x330 [cfg80211 0000000000000000000000000000000000000000]
[ 4263.398019]  ? nl80211_send_scan_start+0x489/0x700 [cfg80211 0000000000000000000000000000000000000000]
[ 4263.398039]  ? genl_family_rcv_msg_doit+0x100/0x160
[ 4263.398044]  ? genl_rcv_msg+0xee/0x1e0
[ 4263.398047]  ? nl80211_send_scan_start+0xa0/0x700 [cfg80211 0000000000000000000000000000000000000000]
[ 4263.398067]  ? genl_get_cmd+0xe0/0xe0
[ 4263.398070]  ? netlink_rcv_skb+0x51/0x100
[ 4263.398073]  ? genl_rcv+0x24/0x40
[ 4263.398076]  ? netlink_unicast+0x234/0x370
[ 4263.398079]  ? netlink_sendmsg+0x250/0x4d0
[ 4263.398082]  ? sock_sendmsg+0x5f/0x70
[ 4263.398086]  ? __sys_sendto+0x113/0x160
[ 4263.398090]  ? __x64_sys_sendto+0x20/0x30
[ 4263.398092]  ? do_syscall_64+0x5b/0x80
[ 4263.398097]  ? __x64_sys_epoll_wait+0x6f/0x110
[ 4263.398101]  ? syscall_exit_to_user_mode+0x23/0x50
[ 4263.398105]  ? do_syscall_64+0x67/0x80
[ 4263.398108]  ? __x64_sys_epoll_ctl+0x6c/0xa0
[ 4263.398111]  ? syscall_exit_to_user_mode+0x23/0x50
[ 4263.398113]  ? do_syscall_64+0x67/0x80
[ 4263.398116]  ? entry_SYSCALL_64_after_hwframe+0x61/0xcb
[ 4263.398121]  </TASK>
```

Hence, I'll close this. You can try reporting a bug against the kernel.

**Comment by davmac314** [comment]
Not sure why it's saying "not planned". Real reason is not-a-bug as outlined above.
