### ISSUE TITLE
"-l /var/log/dinit.log" does nothing?

### ISSUE THREAD

**Issue by IngwiePhoenix** [davmac314/dinit#147]
Hello!

I have `dinit` happily chugging along and working as intended - for the moment, anyway.

While creating my first service, for Caddy, I intentionally left a typo in the command line, to see what the "debugging" experience would be like.

First, this is how `dinit` runs right now:

```
root@FriendlyWrt /s/dinit.d# cat /etc/init.d/dinit
#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

start_service() {
        procd_open_instance dinit
        procd_set_param command /sbin/dinit -d /sdcard/dinit.d --log-file /var/log/dinit.log
        procd_close_instance
}
root@FriendlyWrt /s/dinit.d# ps -ef | grep dinit
15131 root      0:00 /sbin/dinit -d /sdcard/dinit.d --log-file /var/log/dinit.log
18727 root      0:00 grep --color=auto dinit
```

However, the specified log file does not exist.

```
root@FriendlyWrt /s/dinit.d# ls -1 /var/log
caddy.dinit.log
caddy.log
lastlog
log.nmbd
log.smbd
mysql
php8-fpm.log
rclone
samba
tor
wtmp
www.access.log
```

Did I miss something about that option? I didn't spot anything int he man pages.

Thanks and kind regards,
Ingwie

**Comment by davmac314** [comment]
Confirmed, there seems to be a bug. According to my testing it works in user service manager mode (`-u`) so that's a possible workaround (you can specify both `-u -p /run/dinitctl` to effectively get a system service manager anyway). I'll investigate further when I get a chance.

**Comment by davmac314** [comment]
Actually, with a quick look at the code, I think the bug is in this line in dinit.cc (line 579 in current master):
```
    if (!am_system_init && log_specified) setup_external_log();
```
I think that the `&&` should be `||`.

**Comment by IngwiePhoenix** [comment]
`IF i am system init AND log is specified` sounds off, yeah. :)

**Comment by davmac314** [comment]
It's actually `IF i am NOT system init AND log is specified` at the moment :) That is why it works when `-u` is supplied (that sets `am_system_init` false).
