### ISSUE TITLE
[UNRELEASED] 0.17.0pre: `/run/dinitctl` is not created!

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#148]
Hi. I update my Dinit to 0.17.0pre to test new cool `triggered` services but seems like Dinit refuse to create `/run/dinitctl` socket. I use Example services in Dinit and just updated my Dinit. I test Dinit in `single` mode and dinitctl socket is available (and It's doesn't contain `starts-rwfs` option!).
Something need to be changed?
my `rootrw` service:
```
# Re-mount the root filesystem read/write.

type = scripted
command = /bin/mount -n -o remount,rw /
restart = false
options = starts-rwfs
logfile = /run/rootrw.log

depends-on = early-filesystems
depends-on = udevd
waits-for = hwclock
waits-for = rootfscheck
```

Regards

**Comment by davmac314** [comment]
It works for me.

If you boot via `single` and it can create the socket then, that means `/run` is somehow already writable. Dinit will create the socket immediately when it starts in that case. One of the example services mounts a tmpfs on `/run` so that would make the socket unavailable.

You need to tailor the example services according to the specifics of your actual system; they are not intended to be used as-is.

**Comment by davmac314** [comment]
See https://github.com/davmac314/dinit/issues/57

**Comment by davmac314** [comment]
>  I test Dinit in single mode and dinitctl socket is available (and It's doesn't contain starts-rwfs option!).

See the documentation for the option:
> ... This prompts Dinit to attempt to create its control socket, **if it has not already managed to do so**, ...

**Comment by mobin-2008** [comment]
The main problem is Dinit refuse for creating `/run/dinitctl` socket in 0.17.0pre (but works fine in 0.16.0). I have two services contain `starts-rwfs` option to request Dinit to create his socket. [`early-filesystems`](https://github.com/davmac314/dinit/blob/master/doc/linux/services/early-filesystems) and [`rootrw`](https://github.com/davmac314/dinit/blob/master/doc/linux/services/rootrw). Seems like I need to create a service with `pass-cs-fd` and `runs-on-console` to figure out about this thing.

Thanks for your information.

**Comment by mobin-2008** [comment]
I create a `tty1-debug` as below:
```
type = process
command = /bin/bash
options = runs-on-console
options = pass-cs-fd

depends-on = rcboot
```
I expect to see `$DINIT_CS_FD`sh is available. I request `dinitctl --use-passed-cfd list` to see what services are started and everything is started except:
* [`loginready`](https://github.com/davmac314/dinit/blob/master/doc/linux/services/loginready) (due to `runs-on-console`)
* [`sshd`](https://github.com/davmac314/dinit/blob/master/doc/linux/services/sshd) (due to `loginready`)
* `sysvinit-services` (due to `loginready`)

I created `test-rootrw` as follows:
```
type = scripted
command = true
options = starts-rwfs
```
and run it with `dinitctl --use-passed-cfd start test-rootrw`. I expect Dinit creates his socket but Dinit refuse to do that. I trace Dinit's syscalls to see whats happens and posted it at end of this comment. Also I look at my `dmesg` and don't see any thing related to Dinit (posted at end). Also I confirm `/run/` is writable.

Regards

<details>
<summary>strace: `strace -p 1 2> /run/dinit-strace.log`</summary>

```
strace: Process 1 attached
epoll_wait(3, [{EPOLLIN, {u32=3397590472, u64=94904994962888}}], 16, -1) = 1
epoll_wait(3, [], 16, 0)                = 0
read(14, "\0", 919)                     = 1
write(14, ":\1\0\2\0", 5)               = 5
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
epoll_wait(3, [{EPOLLIN, {u32=3397590472, u64=94904994962888}}], 16, 0) = 1
epoll_wait(3, [], 16, 0)                = 0
read(14, "\2\v\0test-rootrw", 918)      = 14
write(14, ";\2\5\0\0\0\2", 7)           = 7
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
epoll_wait(3, [{EPOLLIN, {u32=3397590472, u64=94904994962888}}], 16, 0) = 1
epoll_wait(3, [], 16, 0)                = 0
read(14, "\4\6\5\0\0\0", 904)           = 6
write(14, "d\21\5\0\0\0\1\1\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\4\0\0\0\1\1\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\3\0\0\0\1\1\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\2\0\0\0\1\1\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\1\0\0\0\1\1\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\0\0\0\0\1\1\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
pipe2([8, 9], O_CLOEXEC)                = 0
epoll_ctl(3, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLONESHOT, {u32=3397592352, u64=94904994964768}}) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f8637054a10) = 687
close(9)                                = 0
timerfd_settime(4, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=724, tv_nsec=260715429}}, NULL) = 0
write(14, "2", 1)                       = 1
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
epoll_wait(3, [], 16, 0)                = 0
epoll_wait(3, [{EPOLLHUP, {u32=3397592352, u64=94904994964768}}], 16, -1) = 1
epoll_wait(3, [], 16, 0)                = 0
read(8, "", 8)                          = 0
epoll_ctl(3, EPOLL_CTL_DEL, 8, NULL)    = 0
close(8)                                = 0
epoll_wait(3, [], 16, 0)                = 0
epoll_wait(3, [{EPOLLIN, {u32=3376571388, u64=94904973943804}}], 16, -1) = 1
read(6, "\21\0\0\0\0\0\0\0\1\0\0\0\257\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 128) = 128
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 687
wait4(-1, 0x7fffc7cc52ec, WNOHANG, NULL) = 0
read(6, 0x7fffc7cc52f0, 128)            = -1 EAGAIN (Resource temporarily unavailable)
signalfd4(6, [INT QUIT TERM CHLD], 8, SFD_CLOEXEC|SFD_NONBLOCK) = 6
epoll_wait(3, [], 16, 0)                = 0
timerfd_settime(4, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}, NULL) = 0
write(14, "d\21\5\0\0\0\0\2\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\4\0\0\0\0\2\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\3\0\0\0\0\2\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\2\0\0\0\0\2\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\1\0\0\0\0\2\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
write(14, "d\21\0\0\0\0\0\2\2\10\0\0\0\0\0\0\0", 17) = 17
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLONESHOT, {u32=3397590472, u64=94904994962888}}) = 0
epoll_wait(3, [], 16, 0)                = 0
epoll_wait(3, strace: Process 1 detached
 <detached ...>
```

</details>

[dmesg.txt](https://github.com/davmac314/dinit/files/10510991/dmesg.txt)
Regards

**Comment by davmac314** [comment]
Are you sure dinit didn't create the socket (in `/run`), and then one of the services (eg `early-filesystems`) mount tmpfs over the top of it?

You've said in issue 57 that your `/run` is writable on boot when dinit starts. So that's when dinit creates the socket, not when you start any service. As I said above:

> I.e. the starts-rwfs option isn't necessary to create the control socket if the control socket can be created when dinit starts.

**Comment by davmac314** [comment]
In case what I've said isn't clear: if dinit has already created the socket, it won't do it again. So if it's creating the socket at initial startup (which it should be, on your system, since the `/run` directory is writable) then starting a service with `starts-rwfs` option won't have any effect on the socket creation.

So, I believe the most likely reason you aren't seeing the socket is not because dinit hasn't created it, but because dinit _has_ created it already and one of the services is _hiding_ it (eg. mounting a filesystem over the top of `/run`) or deleting it.

**Comment by mobin-2008** [comment]
Yes, You right. I comment out mounting `tmpfs` over `/run` in `early-filesystems` and everything going correct. I wonder why I don't see this issue in <=0.16.0.

**Comment by davmac314** [comment]
Maybe due to 7c3fc11cda7ae50ca4eb348feead7ae001cb7874 - not sure, maybe I should partially revert this change.

**Comment by mobin-2008** [comment]
I suggest tell users about this case in 0.17.0 release page and NEWS, "this behaviour is deprecated and users must don't use it". After a peroid of time we can remove that. No?

**Comment by davmac314** [comment]
> I suggest tell users about this case in 0.17.0 release page and NEWS, "this behaviour is deprecated and users must don't use it". After a peroid of time we can remove that behaviour. No?

The change has reverted so as far as I am concerned there is nothing that can be said in NEWS. I did add a change to the documentation for the `starts-rwfs` option, that recommends not relying on the behaviour.
