### ISSUE TITLE
Unknown setting: onstart

### ISSUE THREAD

**Issue by fpoussin** [davmac314/dinit#16]
This happens on 0.5.1 using the default init files

 ```
[    3.298816] Run /sbin/init as init process
dinit: early-filesystems: Unknown setting: onstart
No shutdown was requested; boot failure? Will re-run boot sequence.
Press Enter to continue.
```
The file: https://github.com/davmac314/dinit/blob/v0.5.1/doc/linux/services/early-filesystems

Did I miss something?
Thanks

**Comment by davmac314** [comment]
The setting names have changed since the sample config was added, I have updated it now (on development branch). Thanks!

**Comment by fpoussin** [comment]
That worked, thanks!
