### ISSUE TITLE
Properly creating a dependency chain

### ISSUE THREAD

**Issue by IngwiePhoenix** [davmac314/dinit#167]
So I have been using dinit on my OpenWrt box for a while now and it has worked exactly the way I wanted it to. Now, however, I want to get into more advanced topics as I am setting up more services as my network becomes more complete. The first thing I want to do properly is dependency chains.

Since my entire dinit setup lives on `/sdcard`, you can easily call it the "init after the init". As such, it is supposed to inherit a few things from the OS' actual init in a meaningful way. On OpenWrt, the running state of a service can easily be checked with `/etc/init.d/$service running`, which will exit 0 if it is, 1 if it is not. In order to solve a few dependencies on my end, I want to integrate that into dinit.

So before starting `caddy`, I want to make sure the network is up, which `/etc/init.d/network` can tell me. So I imagine that in dinit, I would use something like this:

```
# dinit.d/os-network
type = script
command = /etc/init.d/network running
```

And in `dinit.d/caddy`, would I specify `wait-for` or `depends-on`?

When I tried setting this up with kopia depending on caddy, it failed to start kopia a lot, so I eventually just gave up on it and commented it out, just hoping it'd work - untill I removed Kopia alltogether because it just didn't do what I wanted, at all.

And as an aside, have you considered templated units? I saw this in SystemD, which I think would be genuely handy where you can specify a `someservice@.service` and use `%i` to be substitued to whatever was used on the command line or dependency - like `someservice@foo`. In my case, it'd probably be `os@networking`.

The other thing I am wondering about is retrying. Say dinit starts, but the network is not ready (thus the above `os-network` unit fails), how can I make dinit retry at a later point? Say I want Caddy to retry five times every 5 seconds, where each try is about half a second apart from each other - and if it fails a total of 20 times, give up.

Thanks for this awesome init system, I genuely enjoy using it. Super easy, straight forward and very, very reliable. :) I have to review my OpenWrt files, but I plan to put it into a PR against the package repos for other OpenWrt users, because dinit + apk packages (like ipfs) are genuely a great way to build custom things that can just live on additional storage.

Kind regards,
Ingwie

PS.: I am also working on using dinit as a replacement for the OpenLGTV "root" to set up mounting the USB stick, launching Syncthing and thus automating a few things whenever the TV turns on so my RetroArch savedata is always exactly where it needs to be. That'll be a fun thing... :)

**Comment by mobin-2008** [comment]
Hi!
About networking, Do you can upload `/etc/init.d/networking` file content (or a link to official git repo etc)?

**Comment by IngwiePhoenix** [comment]
https://github.com/openwrt/openwrt/blob/master/package/network/config/netifd/files/etc/init.d/network

This is on the `master` branch, but seems to be the same as on `22.03` (the version I am on).

**Comment by davmac314** [comment]
> So before starting caddy, I want to make sure the network is up, which /etc/init.d/network can tell me. So I imagine that in dinit, I would use something like this:

A service is about having something running or available, not simply checking whether it is running. Maybe I'm misunderstanding but if `/etc/init.d/network running` simply reports whether the service is running (and doesn't actually start it and wait until it _is_ running) then it's insufficient as the command. You need instead a command which starts the network if it isn't already started and _waits_ until it is "running". (I don't know enough about OpenWRTs system to know whether there is such a command). Otherwise, any dependent service will fail to start unless the network is already up.

> And in dinit.d/caddy, would I specify wait-for or depends-on?

The difference is detailed in the [dinit-service man page](https://davmac.org/projects/dinit/man-pages-html/dinit-service.5.html). Basically, if you want the caddy service to continue running when the network stops, use `waits-for`, otherwise use `depends-on`.

**Comment by davmac314** [comment]
> And as an aside, have you considered templated units?

They're not on the current roadmap. I somewhat feel like it should be an external solution, if these are really needed (i.e. use some sort of generator to produce service descriptions from templates, rather than handle it within dinit itself).

> The other thing I am wondering about is retrying. Say dinit starts, but the network is not ready (thus the above os-network unit fails), how can I make dinit retry at a later point?

You can't do that (and it's the wrong approach). The os-network service should wait until the network _is_ ready. That way there's no need to retry.

**Comment by davmac314** [comment]
And finally:

> Thanks for this awesome init system, I genuely enjoy using it. Super easy, straight forward and very, very reliable. :)

Thank you for this feedback! It's great to hear.

**Comment by mobin-2008** [comment]
About networking, I suggest use `/etc/init.d/network start` in `/etc/dinit.d/os-network` as command. It's most eaiser way if it's works. if not you can try this:

Use triggered type services: triggered services helps to integrate other programs into dinit but those're more complicated. For example:
if `start_service()` is where is network will be ready, add this line to end of that function:
```sh
/sbin/dinitctl trigger os-network
```
and replace current os-network with this:
```sh
type = triggered
```
Done! Just make sure os-network service has started before /etc/init.d/network script and You have latest git commit of Dinit!

What happens:
1. PID 1 (busybox, right?) starts Dinit
2. Dinit starts `os-network` and it's waits for be triggered (stuck at `STARTING` state)
3. PID 1 starts `network`
4. `network` service triggers `os-network` service via `dinitctl` when network daemon is ready
5. `os-network` changes its state to `STARTED`
6. done

Regards

**Comment by davmac314** [comment]
> Use triggered type services: triggered services helps to integrate other programs into dinit

Note that this will only work reliably if it is guaranteed that dinit is already running when the network starts.

**Comment by mobin-2008** [comment]
> > Use triggered type services: triggered services helps to integrate other programs into dinit
> 
> (Also, I don't recommend running a non-release build).

I edited my message to include some warnings about triggered services.

**Comment by davmac314** [comment]
@IngwiePhoenix are we good to close this issue?
