### ISSUE TITLE
change restart default behavior to true?

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#168]
IMO, the default of `restart` being `false` is rather bizarre and not matching pretty much any other service manager. I find myself adding `restart = true` to pretty much any supervised service. Would you be open to reconsidering the default value?

**Comment by davmac314** [comment]
Sure, changing the default should be fine. In general I prefer having less behaviour that is implicit, but if there's a trade-off with convenience we can change it and document accordingly. (Note however that systemd's default is also to not restart, so dinit is not completely alone in the current behaviour).
