### ISSUE TITLE
default service path for ephemeral services

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#173]
it would be good to have a tmpfs path among the default service file paths, e.g. in `/run/dinit.d` or something; it would be a good place for services generated at runtime (i'm thinking e.g. ephemeral units generated from dbus .service files for dbus activation with a custom dinit controller)

perhaps having some kind of support for systemd-style unit generators would also be good, but i'm thinking perhaps that can already be done without doing anything in dinit, all it would take is a custom service on early boot that runs the generators (which would output their service files in the special `dinit.d`) and then things could easily depend on these later in the boot..

**Comment by davmac314** [comment]
I've added `/run/dinit.d` to the default system service paths; perhaps more will be needed to support the kind of services you're thinking of, but let's see how it goes.
