### ISSUE TITLE
unifying the data types for socket communication

### ISSUE THREAD

**Issue by james-knippes** [davmac314/dinit#179]
dinit and dinitctl define some  data types used in socket communication in different places/headers.
E.g.:
- `control.cc` gets the definition of  `handle_t` from the `control_conn_t` class in  `control.h`
- `dinitctl.cc` gets it's definition of `handle_t` directrly from from `dinit-client.h`

If the type used for socket communication has to be changed this has to be done/tracked in two different places.
I would suggest creating the a common header for types used in the communication protocol.  Maybe pull them all in `includes/control-datatypes.h` and go through the code moving the used datatypes there?
I could create a mr if there are no general objections?

**Comment by davmac314** [comment]
I'm not opposed, thanks.

**Comment by mobin-2008** [comment]
Addressed by #250
