### ISSUE TITLE
Dinitctl should use system socket when dinit used as init

### ISSUE THREAD

**Issue by fpoussin** [davmac314/dinit#18]
According to https://github.com/davmac314/dinit/blob/master/src/dinitctl.cc#L292 if the socket path is omitted, it should default to ~/.dinitctl
This does not work when ran as init since the socket is created at /dev/dinitctl and we get `dinitctl: connect: No such file or directory` instead.

**Comment by davmac314** [comment]
Well, `dinitctl` can't know whether dinit is running as init or not, so it has the `-s` switch to talk to the "system" instance (which an instance running as init will be). So you can use eg:

`dinitctl -s list`

However, it is inconsistent that `dinit` runs as the system process when run as root, but `dinitctl` talks to the user process by default even when run as root. I've been thinking about changing that.

**Comment by fpoussin** [comment]
Maybe -s should be the default? At least when ran as root.

**Comment by davmac314** [comment]
> Maybe -s should be the default? At least when ran as root.
Yes, this is exactly what I was thinking.
