### ISSUE TITLE
Support for multiple sockets per service

### ISSUE THREAD

**Issue by 62832** [davmac314/dinit#195]
This was previously asked about [in a discussion last year](https://github.com/davmac314/dinit/discussions/70), but would it be possible for dinit to eventually support defining multiple sockets for a given service?

One service that would immediately benefit from this would likely be a service for `gpg-agent` as it typically uses four different sockets when daemonised depending on the kind of application attempting to communicate with it. Though, in general, maybe this could be useful for any service that would typically make use of `.socket` files under a systemd distribution?

**Comment by davmac314** [comment]
It would of course be possible but there are no plans for it at this stage.

I don't actually see how it would be useful for any service that makes use of `.socket` files; it seems like it would be only useful for services that need multiple sockets, unless I'm missing something?

**Comment by davmac314** [comment]
Incidentally, the only reason this seems to be useful for gpg-agent is that its interface is poorly though-out. If run `--supervised` then it _requires_ the sockets to be pre-opened, but there's really no good reason that I can see for that to be case. You should consider opening an issue with GPG.

Also, please note that for Dinit I don't normally accept feature requests without a patch (or willingness to work on the issue). There are some exceptions, see the README.

**Comment by davmac314** [comment]
> I wish I could help in that case, but my knowledge of C and deeper related UNIX concepts is, for all practical purposes, non-existent. My apologies.

It's no problem at all, in this case it's a legitimate feature for service management (though not one I will be giving any priority to at least for now, sorry). I just wanted to flag the "no feature requests without a patch" policy at this point to as a general reminder (to anyone reading this issue), not because this particular request is invalid. Thanks.

**Comment by davmac314** [comment]
That is also a question for the gpg developers, I'm afraid.
