### ISSUE TITLE
quiet

### ISSUE THREAD

**Issue by jackffmm** [davmac314/dinit#197]
I'd like an option to just see a black screen if no errors. Like systemd when you use the kernel params 'quiet' and 'loglevel=0'.

**Comment by jackffmm** [comment]
Oh great! ill test it, thanks!
> we don't take feature requests
since when ? :)

**Comment by davmac314** [comment]
> since when ? :)

Feature requests are welcome if they come with a patch or willingness to work on one :)
This is documented in the README.

**Comment by jackffmm** [comment]
ok, no its not passed here. but on systemd its somehow passed ?

**Comment by davmac314** [comment]
It's possible that systemd processes `/proc/cmdline` which contains the kernel command line.

**Comment by jackffmm** [comment]
hmm ok, thanks
