### ISSUE TITLE
Add Fish Completion

### ISSUE THREAD

**Issue by iacore** [davmac314/dinit#201]
I wrote a simple completion script [here](https://gist.github.com/iacore/6d6d4dd56e12fc6437b5444bd9fa7b78). Place it under `~/.config/fish/completions/dinitctl.fish` to install.

slight problem: `dinitctl list` doesn't have structured output. This might be flaky

TODO
- [ ] long/short opts for sub-commands

**Comment by davmac314** [comment]
Thanks, I'll drop this into a `contrib` folder at some point

**Comment by davmac314** [comment]
Done in 2f783d167333898d41f3a1b88a4af9e93bb6ea9f
