### ISSUE TITLE
reboot/shutdown may get stuck if triggered while a service is still coming up

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#225]
If there is a service that is in the process of coming up (i.e. the process has started but readiness has not been triggered), shutdown/reboot may get stuck, as dinit will seemingly not take down the service that is still being waited on, and that service may never finish starting. I've been noticing this e.g. with a Chrony service, which will wait for ntp sync (https://github.com/chimera-linux/cports/blob/master/main/chrony/files/chrony , https://github.com/chimera-linux/cports/blob/master/main/chrony/files/chronyd) which may take a while. IMO dinit should eagerly take down unreadied processes on shutdown.

**Comment by davmac314** [comment]
I think that `options = start-interruptible` would solve this. With that option Dinit will be happy to try and take the service down while it's still starting. Without it, Dinit plays safe and assumes that interrupting service startup isn't a good idea.

**Comment by q66** [comment]
hm, good point; i will check this later

that said, IMO it should generally be safe to take down startup of anything if you're actually shutting down or rebooting (though not necessarily if the state change happens due to something else)

**Comment by q66** [comment]
indeed, appears to have solved the issue; i'll just close this then
