### ISSUE TITLE
Improve service type documentation

### ISSUE THREAD

**Issue by jackffmm** [davmac314/dinit#231]
Im not an expert but I've read the [man](https://davmac.org/projects/dinit/man-pages-html/dinit-service.5.html#SERVICE_TYPES) 100 times and im still not sure of the differences between the types: process, bgprocess and scripted, and every time I need to write a new service i have to read it again and usually I pick the wrong one.
May I suggest to rewrite that paragraph of the docs ? And maybe add a comparison table with X and V of the features.
Thanks.

**Comment by davmac314** [comment]
The difference between bgprocess and process services is there in the docs:

> This [bgprocess] kind of service is similar to a regular process service, but the process daemonizes or otherwise forks from the original process which starts it, and the process ID is written to a file.

For scripted services the service state is not tied to an executing process, so once the start command completes then the service is considered started (and when stopping, once the stop command completes then the service is considered stopped).

I will tweak the wording.

**Comment by jackffmm** [comment]
where is my second comment ? have you deleted it ?

**Comment by davmac314** [comment]
I haven't seen any other comment from you on this issue

**Comment by jackffmm** [comment]
damn, i forgot to post! it was 100 lines...

**Comment by jackffmm** [comment]
in short:
- process:
-- the sentence "starting the service simply requires starting the process; stopping the service is accomplished by stopping the process" im not sure what that means!
-- are supervised ?
- bgprocess:
-- whats the difference between fork(or daemonization) and to not fork ?
- scripted:
-- these basicly are not supervised... so why this name ?
-- really a process started by the script can be supervised ?
- triggered services:
-- why these have the limitation of the internal scripts ?
-- after a quick look I cant find how to set the trigger condition...

**Comment by davmac314** [comment]
> the sentence "starting the service simply requires starting the process; stopping the service is accomplished by stopping the process" im not sure what that means!

It means exactly what it says. I can only guess at why you find it unclear. Do you find this better:

"dinit starts the service by starting the process, and stops the service by stopping the process."

? If not, can you explain further why it is unclear?

Yes, the process that runs as part of a process service is supervised. That should be clear from the modified text: "_The service's start/stopped state is linked to the state of its associated process_"

> whats the difference between fork(or daemonization) and to not fork ?

Again, exactly as it says. One forks and the other doesn't. Is the problem that you don't know what "fork" means, or something else?

> scripted:
-- these basicly are not supervised... so why this name ?

The service state is altered via a script (command).

> really a process started by the script can be supervised ?

I don't understand the question. A process started by the start script cannot be supervised by dinit. _scripted_ services do not necessarily even run a process (outside the start/stop commands), so there is usually nothing to supervise.

> triggered services:
-- why these have the limitation of the internal scripts ?

The alternative would be to have every type of service support triggered start, which could have been done but would be a more complicated implementation. Internal services are limited only in the sense that they do not have a process associated with them and that starting/stopping them doesn't require any external action of the part of dinit. You can still have process/bgprocess/whatever services depend on triggered services, so if you need to delay startup of another service by an external trigger, you can do it that way.

> -- after a quick look I cant find how to set the trigger condition...

You can't set a trigger condition within dinit. The trigger is external: _an external trigger is required before they will start_

And:

_The dinitctl trigger command can be used to trigger such a service; see dinitctl(8)_

**Comment by jackffmm** [comment]
> Do you find this better...?

yes! much better!
>Is the problem that you don't know what "fork" means, or something else?

I know what fork means in general, not in a init... but the point is that I still dont know the difference between process and bg process !
> I don't understand the question. A process started by...

I think i understand now...
> The alternative would be to have every type of service support triggered...

Ok, whats the difference between `dinitctl start` and `dinitctl trigger` ?

**Comment by davmac314** [comment]
> I know what fork means in general, not in a init... but the point is that I still dont know the difference between process and bg process !

A `bgprocess` is a "background process":
> Bgprocess services ("background process" services)

A `bgprocess` forks from the original process.
> the process "daemonizes" or otherwise forks from the original process which starts it, and writes its new process ID to a file

A normal `process` doesn't do this. That is the difference. It is actually there in the description:

> This kind of service is similar to a regular process service, **but** the process "daemonizes" or otherwise forks from the original process which starts it

With a `process` service the process will just run. It might have a process ID of 100, for example.

With a `bgprocess` services the process will start with process ID (let's say 101), but it forks from that to create a new process (102). The original process writes the new process ID to a file and then terminates.

> Ok, whats the difference between dinitctl start and dinitctl trigger ?

dinitctl start: starts the service. The service becomes "starting". Once the startup is complete it becomes "started". If it's a `triggered` service, the startup won't be complete until the trigger is issued, it will remain "starting" until that time. This is documented:

> Triggered services are similar to internal processes, but an external trigger is required before they will start (i.e. their startup will pause until the trigger occurs)

dinitctl trigger: sets the trigger for a triggered process, so that it can finish starting.

>        trigger
>              Mark the specified service (which must be a triggered service)
>              as having its external trigger set.  This will allow the service
>              to finish starting.

**Comment by jackffmm** [comment]
I partially understand the technical part of of bgprocess, but I STILL dont know what to pick and why if i have to write a service !

Ok now i understand the triggered service... but the description should be more like how u told me here

**Comment by davmac314** [comment]
> I partially understand the technical part of of bgprocess, but I STILL dont know what to pick and why if i have to write a service !

You have to pick the one that matches the behaviour of the process that you are writing a service for. If it tries to background itself then you use `bgprocess`. Otherwise you use `process`.

For example, `smbd` (https://www.samba.org/samba/docs/current/man-html/smbd.8.html) backgrounds itself by default. It also has an option (`-F`) to run "in the foreground", so you can use a `process` if you put `-F` on the command line, otherwise you would need to use a `bgprocess`. Some programs just always behave one way or another, so you have to pick `process` or `bgprocess` accordingly.

> Ok now i understand the triggered service... but the description should be more like how u told me here

I'll think about how to rework it a bit.

**Comment by jackffmm** [comment]
After reading the systemd guides, I think I understood the bgprocess, basicly u use it for processes that will fork !
Later ill write my version of the descriptions, maybe u can be inspired :)

A off-topic question if u dont mind; if the process has the option and i decide if it will fork (like smbd), how is better to run it ? to fork or not to fork ?

**Comment by davmac314** [comment]
> A off-topic question if u dont mind; if the process has the option and i decide if it will fork (like smbd), how is better to run it ? to fork or not to fork ?

In practice, it doesn't matter much. I normally prefer `process` (non-forking) because forking is an extra step which is ever-so-slightly less efficient (and it also requires additional complexity in Dinit to handle properly).

**Comment by jackffmm** [comment]
ok, my version:
process: this kind of service will execute and supervise one process, that will be terminated when the process stop.

bgprocess: this kind of service must be used with applications that forks and will be supervised reading the process id from a file.

scripted: this kind of service is not supervised and will only execute a start and a stop command, that can be a script. If the commands returns an error the service will not be considered started.

triggered: this kind of service are similar to internal services, but once started they must be triggered using the dinitctl trigger command to really be started.


Probably some technical details is missing here...

**Comment by davmac314** [comment]
Wording has been adjusted.
