### ISSUE TITLE
Configure script does not add compiler flags (inc. optimisation) to LDFLAGS when using LTO

### ISSUE THREAD

**Issue by davmac314** [davmac314/dinit#232]
If LTO is used the optimisation and code generation options (-Os, -fno-plt etc) need to be passed to the linker as well as compiler. The configure script currently gets this wrong, i.e. it generates:

```
CXXFLAGS=-std=c++11 -Wall -Os -fno-plt -fno-rtti -flto
...
LDFLAGS_BASE=
LDFLAGS=$(LDFLAGS_BASE) -flto
```

(Note that LDFLAGS_BASE was just added). For non-configure builds, instead:

```
CXXFLAGS=-std=c++11 -Os -Wall -flto -fno-rtti -fno-plt
...
LDFLAGS_BASE=
LDFLAGS=$(LDFLAGS_BASE) $(CXXFLAGS)
```

**Comment by mobin-2008** [comment]
Umm, One question, this new option can be used by users, right? So why it doesn't present in configure help message and doesn't catched by argument parser? @davmac314 Did you forgot to add it and I should add it or there is something I can't understand?

**Comment by davmac314** [comment]
> Umm, One question, this new option can be used by users, right?

You mean `LDFLAGS_BASE`? It can be used by users at build time, for convenience (see BUILD). I didn't add full support for it to configure since it's not really necessary but you can do that if you want.
