### ISSUE TITLE
`env-file` doesn't work on dinit 0.17.0

### ISSUE THREAD

**Issue by crabvk** [davmac314/dinit#238]
Updated dinit from 0.16.1 to 0.17.0 on Artix Linux and `env-file` stopped working.
Runnig dinit as a regular user with `dinit -q -l $HOME/log/dinit.log`.
Script I used to test `env-file` (*~/.config/dinit.d/cmd.sh*):
```bash
#!/usr/bin/env bash
echo $WAYLAND_DISPLAY
```
Dinit service file:
```dinit
type = scripted
command = /home/crabvk/.config/dinit.d/cmd.sh
env-file = $HOME/.config/dinit.d/env.conf
restart = false
logfile = $HOME/log/cmd.log
```
*~/.config/dinit.d/env.conf* contains:
```bash
WAYLAND_DISPLAY=wayland-1
```
If I run `dinitctl start cmd` with dinit 0.16.1, the log (*~/log/cmd.log*) contains `wayland-1`.
If I run the same command with dinit 0.17.0 the log contains one empty line.

**Comment by mobin-2008** [comment]
from [`dinit-service(5)`](https://davmac.org/projects/dinit/man-pages-html/dinit-service.5.html) man-page:
> [env-file = file](https://davmac.org/projects/dinit/man-pages-html/dinit-service.5.html#env)
    Specifies a file containing value assignments for environment variables, in the same format recognised by the dinit command's --env-file option (see dinit(8)). The file is read when the service is loaded, therefore values from it can be used in variable substitutions (see VARIABLE SUBSTITUTION). **Variable substitution is not performed on the env-file property value itself.**

So you need to replace `$HOME` with your actual home path. I think it should show a warning (or error) if it cannot read env-file.

**Comment by crabvk** [comment]
Yes, that was the issue, thank you.
