### ISSUE TITLE
[Documentation] Using dinit on LFS/BLFS - could a subsection be added to the main README.md or elsewhere?

### ISSUE THREAD

**Issue by rubyFeedback** [davmac314/dinit#24]
Hey Davin,

Not sure if you have time/energy, but it may be interesting to see how to use and apply dinit to a LFS/BLFS setup (linux from scratch / beyond linux from scratch).

E. g. ideally a short recipe how to get that to work, for people who never before used dinit but would like to try it out. Please feel free to close this if this seems too much work or is otherwise not wanted, no problem!

**Comment by davmac314** [comment]
Hi! Thanks for the suggestion. You're right that I'm short of time but I'm happy to accept this ticket (and either get to it later, or maybe someone else will be able to contribute).

FWIW it shouldn't be too hard to:

1. Set up an LFS system as per the book
2. Compile and install Dinit in the default location
3. Set up Dinit boot scripts based on those provided in the repository ([doc/linux/services](../tree/master/doc/linux/services)). You probably want to cross-reference this with the [LFS boot scripts](http://www.linuxfromscratch.org/lfs/view/stable/chapter07/bootscripts.html) and their [usage documentation](http://www.linuxfromscratch.org/lfs/view/stable/chapter07/usage.html).
4. Test by booting with "init=/sbin/dinit" appended to the kernel command line
5. Eventually remove Sys V init and link /sbin/init to /sbin/dinit

**Comment by davmac314** [comment]
Although not really specific to LFS, reasonably comprehensive info on setting up Dinit as init for a Linux system is available [here](https://github.com/davmac314/dinit/blob/master/doc/linux/DINIT-AS-INIT.md). Hence I think I'll close this. Any integration with LFS would have to be done by someone else anyway, it's not something I will get around to unfortunately.
