### ISSUE TITLE
loading service env-files relatively to the service file

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#241]
The current behavior appears to treat relative paths as relative to the current working directory dinit was spawned in, which is not very useful, and also confusing.

**Comment by q66** [comment]
@davmac314 what do you think about defaulting the working directory for the service also to the service dir? that would allow consistent behavior for relative commands (which means one could have e.g. a `command = ./scripts/foo.sh ...` for instance)

the current behavior is pretty undocumented, so i don't think as it is users can expect to be able to rely on anything

**Comment by davmac314** [comment]
Yeah, I guess it's ok. The `command =` case is reasonably compelling. I partly think it would be better to resolve the`command =` separately though (so you can still set the working dir to something else). Anyway, what you've suggested is fine for now.
