### ISSUE TITLE
a way to control dinit programmatically

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#254]
I recently started working on https://github.com/chimera-linux/dinit-dbus and right now I'm just invoking dinitctl to perform the actions. However, the output is far from machine-parseable nor it is documented and thus guaranteed to stay stable. I think we need either:

1) A documented/stable socket protocol, perhaps with a public header file containing all the data structures/values being written over the connection
2) Alternatively, having a dinitctl output mode that makes it print stuff in a stable and machine-parseable manner would work equivalently well (and perhaps be a bit easier to use)

**Comment by q66** [comment]
i've started implementing "libdinitctl", a pure C library implementing a high level API around the dinit socket protocol; i'll just figure out the details of the messages from the code for now, but it'd be great if we could ensure things will remain working later

**Comment by davmac314** [comment]
Sounds good, I'll get to documenting the protocol properly when I can. A couple of notes in the meantime:

I recommend always sending `QUERYVERSION` first and checking the returned version is suitable (check the "minimum compatible version"). This command may in future also trigger a compatibility mode, i.e. every "client" should always send `QUERYVERSION` as the first thing.

You should expect an information packet (first byte >= 100, 2nd byte specifies length) at any time, including when expecting a reply from a command packet. (They can be discarded if not processed).

**Comment by q66** [comment]
sure, i figured those out in the meantime, for now i've implemented a working dispatch loop that can be integrated into various event loops, now i gotta actually implement all the APIs...

**Comment by q66** [comment]
btw, this is the initial skeleton for the library: https://gist.github.com/q66/08795f642b007031ecc8e560479d8d32 (api: https://gist.github.com/q66/13ead3be21a9ac14f4b3924b85586e8f)

just to give an idea

**Comment by q66** [comment]
roughly working now: https://gist.github.com/q66/364158b46374c462ea47b38bc5b3f7a4

**Comment by q66** [comment]
https://github.com/chimera-linux/libdinitctl i have published the initial version

still need to handle the rest of the protocol messages and clean things up somewhat, but i'm happy enough with how it works

**Comment by q66** [comment]
it implements the complete protocol now, still need to add a test suite and possilbly clean up the API though

**Comment by q66** [comment]
@davmac314 I'd like to implement recovery in the library, i.e. a way to re-connect to the socket after the connection was dropped for reasons which don't prevent so (such as dinit itself dying)

my current most significant case for that is in the d-bus interface - under such conditions, i want it to report an error from the failed operation, transparently reestablish connection, and start polling on the fresh connection - as not doing so would involve restarting the whole interface, which is not great (as it would require re-requesting the name on the bus etc)

the problem with that is that i'm currently running dinit-dbus from a service with pass-cs-fd and reusing that connection, which is a handy pattern because it requires no knowledge of where the socket is and just works, but it provides me with no way to know where to attempt re-connection when dinit drops the client - do you have any idea if there is some way we could address that?

**Comment by q66** [comment]
though, is it actually necessary for dinit to close the connection upon bad request? replying with BADREQ should leave things consistent as far as i can tell, the client can take it and move on

is there any reason for dinit to ever close the connection, other than if it dies, or if it receives wildly incorrect protocol data (as then it has no idea how much it needs to consume)? right now it's returning badreq+close upon e.g. invalid service handles, which is something we cannot reasonably check clientside (most of the other conditions can be checked clientside)

**Comment by q66** [comment]
hm, or actually, maybe i can check it clientside? cache the returned handle values, and only ever allow passing ones that are present in local cache? perhaps that would solve things without having to implement any sort of recovery (i already client-check most other things which would result in BADREQ)

**Comment by davmac314** [comment]
> though, is it actually necessary for dinit to close the connection upon bad request? replying with BADREQ should leave things consistent as far as i can tell, the client can take it and move on

BADREQ is supposed to mean that dinit doesn't understand the request, i.e. the client messed up the protocol. At that point there's no recovery because the packet stream is not self-synchronising and dinit has no way to know if the client sent a packet that was too large or too small, and if so where the next packet begins. Though I guess for invalid handles it's kind of overkill, conceptually an invalid handle is also a protocol violation and indicative of a possible synchronisation issue between dinit and client, or a client that has mixed up service handles, either of which are situations where you don't necessarily want to continue communication with that client.

We could change the protocol and add a new INVALIDHANDLE reply (which doesn't close the connection) - that would be fairly easy to do I think, and I'd be ok with that, but I'm somewhat in favour of handling it on the client side instead. 

> hm, or actually, maybe i can check it clientside? cache the returned handle values, and only ever allow passing ones that are present in local cache?

That would also work. You would have to watch for UNLOADSERVICE and remove handles used for that, if successful.

Another approach is just leave the obligation on the (library) client to correctly follow protocol. I.e. if an invalid handle is used the connection will be dropped, sure, but this really indicates a client bug and losing the connection is the consequence (which may be better than proceeding with a client that has somehow mixed-up service handles).

**Comment by q66** [comment]
forcing the client to ensure things are correct is bad because in this case a single connection is shared for multiple clients, and doing so lets any client abort it

**Comment by davmac314** [comment]
The library client in this case would be dinit-dbus though, correct? If I understand correctly it's not exposing the connection in a way that gives its own (via D-Bus) clients any way of violating the protocol. The requests are all taking a service by name and not by handle. Or were you planning to change that?

**Comment by q66** [comment]
i will probably just merge dinit-dbus into the same repo with the library and make the dinit-dbus daemon an optional component, and give it identical API as the library; that should be easier to implement and maintain

but i will just add clientside handle caching so there should be no problem

**Comment by q66** [comment]
though, this brings me to yet another thing - won't the presence of a persistent socket connection prevent unloading of services? as far as i can tell in the code, if there is more one listener existing (i.e. the persistent one + user-invoked dinitctl), dinit will prevent unloading?

**Comment by davmac314** [comment]
Yes, handles to a service will currently prevent it from unloading.

I think that maybe there will need to a be a new control command, something like CLOSEHANDLE. Maybe there should also be a way to open "weak" handles which don't prevent service unloading. I could probably implement CLOSEHANDLE this weekend.

**Comment by q66** [comment]
weak handles would probably need new responses from commands, as you don't want to badreq from a weak handle, but you still need the client to know that the handle no longer corresponds to a service

closehandle would be good and probably sufficient, api users can then ensure they are not holding onto a handle for longer than they need to

**Comment by davmac314** [comment]
CLOSEHANDLE implemented in d16f2b705ccecbd8c76a5199a408af8b7a28207d

**Comment by q66** [comment]
hm, I guess I am still not really happy with the way it works when it comes to the d-bus api... I have updated libdinitctl to match the latest protocol and that works great, and should be just fine for C/C++ usage, but for a d-bus api it's no good:

1) since d-bus objects exist globally and their lifetime is not tied to a connection, closehandle is not robust - it's easy to leave dangling handles behind (there is no way to know when a handle has become unnecessary, so the daemon providing the objects cannot perform some kind of garbage collection by itself, and leaving it to the application is bad since it means any random application connecting to the bus can make handles that are left behind
2) i considered dropping the handle concept for d-bus api entirely and always refer to services by name, creating a temporary handle just for the lifetime of the call - which works fine on its own, but precludes implementation of service event signal; this is because service events only happen for valid handles, and since they are out of band, the handle that was created for the original action is by that time already gone

i suppose 2 is a more viable approach (anything that involves keeping global objects that pin stuff in place in a system like this is a no go i guess) - but it would involve relatively complex logic to keep the handle until emission of the service event, and only then drop it (or maybe not so complex? if i assume a single event emission for every potentially waitable action, perhaps i could just always wait for them internally, and close the handle after emission of the signal?)

so perhaps i'll just go with a somewhat more limited, name-driven API instead - in any case, the C API is now complete and i'm fairly happy with how it works

**Comment by q66** [comment]
i think at this point we can close this - i've implemented the complete interface, including the d-bus interface: https://github.com/chimera-linux/libdinitctl

i'll spend a few weeks cleaning it up and stabilizing the interface, as well as add a bunch of tests, and then make a release (won't happen before dinit 0.17.2 anyway)
