### ISSUE TITLE
Make it possible for variables in env-file to be kept empty

### ISSUE THREAD

**Issue by konimex** [davmac314/dinit#258]
First of all, apologies for the title since I don't know how to word it better. I'm not sure to consider this a bug or a feature request since variable substitution in dinit-service file parsing is not shell and understandably, will behave differently.

## How to reproduce

Suppose I want to create `/etc/dinit.d/dhcpcd`, which contains the following

```
type = process
command = /usr/bin/dhcpcd -B -M $INTERFACE
smooth-recovery = true
env-file = /path/to/dhcpcd.conf
```

`/path/to/dhcpcd.conf` contains the following

```
INTERFACE=
```

(note: `INTERFACE=` is intentionally left empty)

I expected it to go on since it's on manager mode (e.g. see below:)

```
dhcpcd-10.0.4 starting
dev: loaded udev
DUID
no interfaces have a carrier
eth0: waiting for carrier
eth0: carrier acquired
```

but it returns error since we don't specify the interface needed:

```
dhcpcd-10.0.4 starting
dev: loaded udev
DUID
: interface not found
```

## Rationale

While it's ideal that any variable is filled properly, it's possible for the default to be empty (and in that case, the program will determine what to do if the variable is empty). For example, in dhcpcd's case, an empty `$INTERFACE` will cause `dhcpcd` to just use manager mode, which uses all available interfaces.

**Comment by davmac314** [comment]
If I understand correctly, what you are really asking for is variable substitution for an empty variable to expand to nothing at all rather than expand to an empty argument, does that sound about right?

It might be a fairly major rework of how variable substitution is currently handled, but I'll have a look when I get a chance.

**Comment by mobin-2008** [comment]
Related: https://forum.artixlinux.org/index.php/topic,6084.0.html

**Comment by konimex** [comment]
> variable substitution for an empty variable to expand to nothing at all rather than expand to an empty argument, does that sound about right?

Yes, I believe that's correct.

**Comment by q66** [comment]
you can just use a script as a command

**Comment by konimex** [comment]
Yes, and I've used that in several occasions.

However, when it comes to personal style preference, using a wrapper script feels really "round-about"-y (for lack of a better word). So I try to avoid it if possible (especially if I'm only dealing with one command, if multiple commands are needed then I'll do it the script way).

**Comment by q66** [comment]
honestly, using env vars for configuration is by itself kinda bad and i don't think it's worth extending dinit's environment handling to further accommodate it

i've been meaning to create a separate tool (perhaps bundle it with dinit-chimera) that will act as a wrapper for commands and implements actual service configuration files and a proper syntax to expand config file entries in the command line, but this is yet to materialize (i've been too busy with other things for now to give it proper thought)

**Comment by davmac314** [comment]
I agree that using environment variables for configuration isn't great. However, I've gone ahead and implemented a solution for this; a new form of expansion written as `$/NAME` (or `$/{NAME}` including all the previously available variations). It's still limited; it breaks up the value by whitespace without any possibility of quoting, producing 0 or more arguments as a result.

Eg if `VAR` is empty (or is unset) then `echo var $/VAR` expands to `echo var` (one argument not two).

If `VAR=one two three` then `echo var $/VAR` expands to `echo var one two three` (four arguments).

In contrast `echo var $VAR` always expands to an `echo` with two arguments.

This is likely the last concession I'll make to more advanced command-line processing within dinit itself. It was always my intention that this sort of thing be done externally to dinit, either by generating service descriptions (with some external template system) or by wrapping the service executable in a script which reads a config file and applies arguments.
