### ISSUE TITLE
closehandle does not enable service to be unloaded

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#261]
If i'm reading this correctly, it is necessary to also remove the listener when closing the last handle to a service, or the service is still stuck in place (as `has_lone_ref` will always fail)

**Comment by davmac314** [comment]
Ugh, github auto-closing issues when a commit is made is not my favourite thing. Anyway, you're right, and the commit ref'd above should address it.

**Comment by q66** [comment]
works fine, thanks
