### ISSUE TITLE
macOS / Darwin build needs different `SBINDIR` and `MANDIR` 

### ISSUE THREAD

**Issue by aidan-gibson** [davmac314/dinit#266]
`/sbin` and `/usr/share/man` are protected by [SIP](https://support.apple.com/en-us/102149#:~:text=System%20Integrity%20Protection%20is%20a,and%20folders%20on%20your%20Mac.). I built very easily by changing `mconfig`, so not a big deal, but just letting ya know a macOS / Darwin user with SIP enabled will get an error if they try to build using the instructions as they currently are. (Thank you for building this btw! Really happy to be using this on macOS.)

**Comment by aidan-gibson** [comment]
Ended up adding it to homebrew https://github.com/aidan-gibson/homebrew-dinit

**Comment by mobin-2008** [comment]
Merged, Thanks :). Also you can add yourself to [`CONTRIBUTORS`](https://github.com/davmac314/dinit/blob/master/CONTRIBUTORS) list if you wish.

**Comment by mobin-2008** [comment]
Fixed in mconfig, configure needs patch, I'm going to fix it.

**Comment by davmac314** [comment]
Instructions have been updated, I'll close this. Thanks for reporting.
