### ISSUE TITLE
`run-as` does not work as advertised

### ISSUE THREAD

**Issue by mskarbek-bnp** [davmac314/dinit#27]
`man` specifies that `run-as` will set group to the primary group of the specified user. Unfortunately that doesn't work, for user `uid=998(gitlab-runner) gid=995(gitlab-runner) groups=995(gitlab-runner)` process with  `run-as` set to `gitlab-runner` works as `gitlab-runner:root`.

`dinit` run as pid 1 (`root:root`) in container.

**Comment by davmac314** [comment]
I'll look into this soon.

**Comment by davmac314** [comment]
This should now work correctly (in 0.8.2).

**Comment by davmac314** [comment]
Can you confirm whether this was fixed in 0.8.2? Thanks

**Comment by davmac314** [comment]
Closing as my own testing indicates this works now.

**Comment by mskarbek-bnp** [comment]
Sorry for not responding earlier, this works fine now. I'm hitting some weird issue with users and Golang programs but at this point I don't think it's dinit related.
