### ISSUE TITLE
bgprocess fails to read pid-file

### ISSUE THREAD

**Issue by mskarbek-bnp** [davmac314/dinit#28]
`dinit` fails to read pid file:
```
dinit: cntlm: read pid file: No such file or directory
[FAILED] cntlm
[  OK  ] boot
cntlm[11]: Daemon ready
```
Process is working correctly and creates pid file in the right place but I suspect that `dinit` tries to read it too soon.
Service file:
```
type = bgprocess
command = /usr/sbin/cntlm -c /etc/cntlm.conf -U cntlm -P /run/cntlm/cntlmd.pid
pid-file = /run/cntlm/cntlmd.pid
restart = true
smooth-recovery = true
options = runs-on-console
depends-on = cntlm-config
```

**Comment by davmac314** [comment]
`dinit` tries to read the pid file as soon as the initial process exits. Programs that background themselves should write the pid file from the initial process, if they don't, there's an unsolvable race (i.e. how should `dinit` know how long to wait?).

The easiest solution in this case is to pass `-f` to `cntlm` command, and change the service type from `bgprocess` to `process`.

**Comment by davmac314** [comment]
(and use `run-as=cntlm` option instead of `-U cntlm`)

**Comment by mskarbek-bnp** [comment]
`-f` and `-U cntlm` works as it should but it's interesting how `systemd` can handle that configuration and is able to track `dinit`. My service file was based on the unit file from the repo package:
```
[Unit]
Description=CNTLM HTTP Accelerator For NTLM Secured Proxies Authenticator
After=network.target

[Service]
Type=forking
EnvironmentFile=-/etc/sysconfig/cntlmd
ExecStart=/usr/sbin/cntlm -c /etc/cntlm.conf -U cntlm -P /run/cntlm/cntlmd.pid

[Install]
WantedBy=multi-user.target
```
