### ISSUE TITLE
Meson generates invalid binary

### ISSUE THREAD

**Issue by PureTryOut** [davmac314/dinit#285]
I've used both the Makefiles and Meson to compile dinit, and the latter generates a garbage binary it seems.

```
$ file  /sbin/dinit
/sbin/dinit: data
```

vs with Makefiles:

```
$ file /sbin/dinit
/sbin/dinit: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, BuildID[sha1]=e14ddc1299e63501c88999dc908b21d04764838c, stripped
```

Build options used are `-Dbuild-shutdown=enabled` and `-Dshutdown-prefix="dinit-"`.

**Comment by nekopsykose** [comment]
do you have the full build+install log of both?

**Comment by PureTryOut** [comment]
I was going to say yes, but I just rebuilt and now it generated a perfectly fine binary... I don't know what happened there, but I suppose it was a local issue :thinking:

**Comment by nekopsykose** [comment]
it definitely seems weird as it's a regular meson executable() with install:true.. so any meson install would ensure it was up to date. really weird!
