### ISSUE TITLE
integration testing

### ISSUE THREAD

**Issue by asherikov** [davmac314/dinit#30]
What is your take on 'integration testing' scenario, i.e., the situation when service crashes must not be recoverable. For example, diinit could start some sort of crash handler service on failure or terminate everything including itself. It looks like `depends-on` is an option, but there is no `depends-on.d`, which is quite inconvenient. It would also be interesting to set default service parameters depending on scenario (testing/production) via service templates.

**Comment by davmac314** [comment]
Well, `depends-on` can be specified multiple times for multiple dependencies. (The same is true for `waits-for`; `waits-for.d` was just meant as a convenience for packaging, i.e. it allows a package to include itself as a soft dependency of another service just by including a symbolic link). So, I don't think there is a major problem here. I wouldn't be against adding a `depends-on.d` option however, and it would be trivial to implement, I think.

As for templating of services, this feels like it is probably outside the scope of Dinit. You could use any templating engine (even just a shell script wrapping `m4` for example) to generate service description files from templates, and then run Dinit with the result.

**Comment by asherikov** [comment]
Ok, thanks for feedback, I have to do some experimenting to see how it may work in my application.
