### ISSUE TITLE
Package in Fedora/EPEL repos

### ISSUE THREAD

**Issue by mskarbek** [davmac314/dinit#31]
I would like to finally publish my package in the main Fedora repo and then add it to EPEL. For that, I would like to have recently added `-o` in a released version. So what's the plan for the next release?

**Comment by davmac314** [comment]
Next release (0.9.0) shouldn't be far away. I'm currently looking into a minor bug with where a service "desired" state is reported incorrectly. I'm aiming to release by next week.

**Comment by davmac314** [comment]
0.9.0 has been released.

**Comment by jhult** [comment]
@mskarbek, any news on this?

**Comment by davmac314** [comment]
I'm going to close this as a won't fix, for now.

**Comment by mskarbek** [comment]
`dinit` is a great project on its own, it just didn't fit into my work anymore, so I moved on to `systemd` when support for it in containers was good enough. if `dinit`could understand and support `systemd` unit files, then it may have some sense to work with it, but rewriting already existing unit files into `dinit` service files each time I introduce a new image and maintain that separately from the upstream projects was not feasible at the scale I have to support.

**Comment by davmac314** [comment]
@mskarbek that's completely understandable. Thanks for the testing and feedback that you gave earlier on, it was greatly appreciated!
