### ISSUE TITLE
single quote in command cannot be parsed

### ISSUE THREAD

**Issue by iacore** [davmac314/dinit#332]
**Describe the bug & Reproduction**

Create a file `dinit.d/a` with this content:

```
type = process
command = /bin/sh -c 'sleep 1 && echo 1'
logfile = /tmp/log-a
```

Then try to start the service. It fails.

```
❯ dinitctl start a
Service 'a' started.

❯ cat /tmp/log-a 
1: -c: line 1: unexpected EOF while looking for matching `''
1: -c: line 1: unexpected EOF while looking for matching `''
1: -c: line 1: unexpected EOF while looking for matching `''
1: -c: line 1: unexpected EOF while looking for matching `''
```

**Expected behavior**
Not sure what is the correct behavior here. Maybe POSIX-compatible shell parsing?

**Additional context**

**Comment by davmac314** [comment]
The correct behaviour is what is documented (in the [dinit-service manpage](https://davmac.org/projects/dinit/man-pages-html/dinit-service.5.html)). The parsing won't ever be POSIX shell compatible, that's definitely a non-goal.

Your example should work if written with double quotes, as:

    command = /bin/sh -c "sleep 1 && echo 1"

**Comment by iacore** [comment]
Thanks for the clarification!
