### ISSUE TITLE
after artix dinit upgrade,  my system stopping to boot untill tmpfiles-setup

### ISSUE THREAD

**Issue by osevan** [davmac314/dinit#347]
When i join in recovery menue and read service file i see no errors.

But what prevents me to boot?

Thanks and

Best Regards
![IMG_20240621_122113_edit_3322737593843505](https://github.com/davmac314/dinit/assets/77795961/4cd2bd3c-2b83-4800-b2fe-2a81916cba07)
![IMG_20240621_122042_edit_3322704757165385](https://github.com/davmac314/dinit/assets/77795961/fa0e010e-82fd-4f68-bef8-f985d7c00c5e)
![IMG_20240621_122004_edit_3322669117852369](https://github.com/davmac314/dinit/assets/77795961/5c4648e8-6d8f-4beb-8f1c-d5be7d1d2259)

**Comment by osevan** [comment]
>
![Uploading IMG_20240621_123121.jpg…]()

**Comment by konimex** [comment]
**Please don't** open an issue in dinit as this issue is unrelated to dinit itself.

[The forum is here, report there instead](https://forum.artixlinux.org/).

**Comment by davmac314** [comment]
As requested, please go through your distribution's support channels.

I will note however that `tmpfiles-setup` is not failing. According to the output you posted, it started fine. Whatever is causing the boot failure is something else - either another service getting stuck, or the tty/login services aren't properly enabled. The problem doesn't occur in my Artix VM.
