### ISSUE TITLE
dinitctl: dinitctl will get stuck when a empty argument is passed as service_name

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#365]
**Describe the bug**
The title is self-explanatory.

**To Reproduce**
1. Use `dinitctl start ""` or `dinitctl enable ""`.
2. Dinitctl is stuck because it pass a empty service name to Dinit daemon but it's unexpected and Dinit will assume that is a partial command and Dinit will wait forever.

**Expected behavior**
It should print a error and then exit without any contact with Dinit.

**Additional context**
I found this when I was trying to fix #363 when I accidentally used `"$SRVICE"` in my dinitctl commands.

**Comment by davmac314** [comment]
The bug is in dinitctl, it should not accept an empty string as a service name.
