### ISSUE TITLE
Remove or at least reduce emulated ARM CI; change CI targets

### ISSUE THREAD

**Issue by davmac314** [davmac314/dinit#378]
The CI runs use 3 ARM targets which are run via some emulation:

- Aarch64 (Alpine)
- Armv6 (Alpine)
- Armv7 (Alpine)

These are slow due to the emulation and possibly inaccurate (the recent Dasynq bug affecting MacOS also affected these emulated runs, but it shouldn't affect the underlying operating system i.e. Linux normally).

I don't think we need them. Dinit is not architecture specific, it is written in portable code. Also, we now get Aarch64 testing via MacOS now anyway.

However, we don't have a single x86(-64) Alpine CI. I think we should.

I suggest we replace the three ARM targets with a single Alpine on x86-64.

@mobin-2008 what do you think?

**Comment by mobin-2008** [comment]
The ARM targets was designed before we have aarch64 MacOS. I think it's enough especially that the main difference between targets is the Standard C/C++ library, C++ compiler and System coreutils. I'm going to replace current Alpine Arm targets with x86_64 one.
