### ISSUE TITLE
[Feature Request] Enable stop-command for process and bgprocess

### ISSUE THREAD

**Issue by konimex** [davmac314/dinit#38]
## Rationale

Certain services, such as `ejabberd`, `prosody` (for process) and `mailman` (for bgprocess), require a stop command to cleanly finish before the process is terminated.

While using `scripted` is also possible, I want to know whether we can supervise these processes or it's a lost cause for these kind of services.

**Comment by davmac314** [comment]
I've thought about this, and at this stage I plan to add support (as you point out it is needed for some applications).

**Comment by davmac314** [comment]
Will try to address this in next version (after 0.13.0).

**Comment by davmac314** [comment]
Implemented for `process` services so far (via [9b3befd](https://github.com/davmac314/dinit/commit/9b3befd49799ba60f3d650a9d160583ef745fcb1))

**Comment by davmac314** [comment]
Implemented in 0.14.0
