### ISSUE TITLE
soft-reboot: Dinit will show "boot failure?" message on soft-reboot

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#382]
**Describe the bug**
The `soft-reboot` command (with #381 patch) or `shutdown -s` will result in `boot failure?` message instead of soft-rebooting and It's a little random because when I use single service it's working as expected but with Chimera default config and services it's not.

**To Reproduce**
1. Build and use Dinit from master branch
2. Use `shutdown -s`
3. Dinit ask for user interaction instead of soft-rebooting

**Expected behavior**
It should soft-reboot the system.

**Additional context**
After #381 I thought it's a good time for testing this new feature. I took a look at code but everything seems to be correct.

**Comment by mobin-2008** [comment]
This should block 0.19 release until it get resolved.

**Comment by davmac314** [comment]
I can't reproduce this.

**Comment by davmac314** [comment]
Are you sure that soft-reboot isn't working at all? Is it possible that soft-reboot executes correctly, but that subsequent service startup fails (services need to be designed to handle soft-reboot properly) which leads to  the boot failure message>

**Comment by mobin-2008** [comment]
My bad 😬. The operation was so fast that I missed the early log.
