### ISSUE TITLE
services with an argument

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#385]
It would be nice if we were able to parameterize services as in systemd `foo@argvalue`; the argument could then be available during variable expansion in command and so on in some form. This is probably not terribly hard to implement so I might take a look at doing it myself, so I'm putting it here so I don't forget, but let me know if you are opposed to the idea or have something better in mind.

**Comment by davmac314** [comment]
I'm not opposed to it, especially if you will implement it yourself :)

**Comment by q66** [comment]
i have an initial version working:

```
q66@chimera: /home/q66/dinit$ ls -l sdir
total 16
-rw-r--r--  1 q66 q66 110 Oct  2 02:20 boot
-rw-r--r--  1 q66 q66  81 Oct  2 02:21 testsrv
q66@chimera: /home/q66/dinit$ cat sdir/boot
type = process
depends-on = testsrv@argvalue
command = /usr/bin/sh -c "echo $1 > test.txt; sleep 10000" sh $1
q66@chimera: /home/q66/dinit$ cat sdir/testsrv 
type = process
command = /usr/bin/sh -c "echo $1 > test2.txt; sleep 10000" sh $1
q66@chimera: /home/q66/dinit$ ./src/dinit --services-dir sdir --socket-path dsock boot@someargval
[  OK  ] testsrv@argvalue
[  OK  ] boot@someargval
^C[STOPPD] boot@someargval
[STOPPD] testsrv@argvalue
q66@chimera: /home/q66/dinit$ cat sdir/test.txt 
someargval
q66@chimera: /home/q66/dinit$ cat sdir/test2.txt
argvalue
```

i'll clean it up, optimize it a bit if possible, and open a PR for review probably during tomorrow...
