### ISSUE TITLE
activatable script/top level service on failure of "boot" one

### ISSUE THREAD

**Issue by JamiKettunen** [davmac314/dinit#387]
On a normal PC when the boot fails you can at least read something on the display (even if not ideal and usually the failing service is way at the top and scrolled past already at the end when all boot services are stopped) and interact with the usual [`Choose: (r)eboot, r(e)covery, re(s)tart boot sequence, (p)ower off? `](https://github.com/davmac314/dinit/blob/116633b/src/dinit.cc#L802) options; however in my use case (a random Android phone with vendor kernel) that's not a practical option due to typically non-functional VT framebuffer (not to mention the need to use a USB keyboard via OTG, so I wrote this pretty bad patch which does work wonderfully for my needs:
```diff
--- a/src/dinit.cc
+++ b/src/dinit.cc
@@ -193,6 +193,9 @@ namespace {
     // These need to be at namespace scope to prevent causing stack allocations when using them:
     constexpr auto shutdown_exec = literal(SBINDIR) + "/" + SHUTDOWN_PREFIX + "shutdown";
     constexpr auto error_exec_sd = literal("Error executing ") + shutdown_exec + ": ";
+    // HYBRIS HACK: Panic command handler in case dinit fails to boot the system
+    constexpr auto panic_exec = literal(SBINDIR) + "/" + "dinit-panic";
+    constexpr auto error_exec_panic = literal("Error executing ") + panic_exec + ": ";
 }
 
 // Options handled in dinit_main
@@ -700,7 +703,17 @@ int dinit_main(int argc, char **argv)
             // Services all stopped but there was no shutdown issued. Inform user, wait for ack, and
             // re-start boot sequence.
             sync(); // Sync to minimise data loss if user elects to power off / hard reset
-            confirm_restart_boot();
+            // HYBRIS HACK: There's likely no working VT for user input in confirm_restart_boot()
+            log_msg_end(" Will run dinit-panic or reboot.");
+            flush_log();
+            sync();
+
+            execl(panic_exec.c_str(), panic_exec.c_str(), nullptr);
+            log(loglevel_t::ERROR, error_exec_panic, strerror(errno));
+            flush_log();
+            sync();
+            shutdown_type = shutdown_type_t::REBOOT;
+
             if (services->count_active_services() != 0) {
                 // Recovery service started
                 goto run_event_loop;
```

Would anything like that be interesting here for upstream? To be clear this more likely would take the form of a `boot`-adjacent "top level service" like `recovery` or maybe `panic` which can be activated via configuration around https://github.com/davmac314/dinit/blob/116633b/src/dinit.cc#L721 instead of calling the hardcoded `confirm_restart_boot()` function assuming working display/keyboard input.

For further context https://github.com/JamiKettunen/chimera-libhybris/blob/8adfd6d/overlays/base/usr/bin/dinit-panic is how I use the feature to setup a USB network between the device side and a host PC it's attached to so I can `ssh` in to inspect and fix "the damage" or whatever may have gone wrong and prevented a normal boot from finishing :)

**Comment by JamiKettunen** [comment]
After a bit more brainstorming and experimentation later I think I can already (without any dinit source changes!) at least implement a part of this feature by editing https://github.com/chimera-linux/dinit-chimera/blob/master/services/early-env with:
```
stop-command = /usr/bin/dinit-panic
stop-timeout = 0
```
I can already override the original `/usr/lib/dinit.d/early-env` with my own custom `/etc/dinit.d/early-env` (after also e.g. `ln -sr /usr/lib/dinit.d/early /etc/dinit.d/early`) so I think this should work out ok.

Now then I just need a way to tell from there if `All services have stopped with no shutdown issued; boot failure?` and if `shutdown_type != shutdown_type_t::NONE` just `exit 0` instead of setting up any USB stuff etc.

The only other thing that "would be nice" is being able to somehow force-launch in my case e.g. `sshd` (via `dinitctl start sshd` instead of [manually running `/usr/bin/sshd` etc in the `stop-command` script](https://github.com/JamiKettunen/chimera-libhybris/blob/c1de360/overlays/base/usr/bin/dinit-panic#L21)) while ignoring the dependencies, but perhaps I missed something and this isn't really that important in the end

**Comment by JamiKettunen** [comment]
That does sound good to me :)

**Comment by JamiKettunen** [comment]
@davmac314 Do you have an idea on how to implement this already (probably quickly if so) or should I try and PR something after getting more familiar with everything?

**Comment by davmac314** [comment]
I would go for a command-line option as the easiest to implement.
