### ISSUE TITLE
[Feature request] Environment variables in command 

### ISSUE THREAD

**Issue by mskarbek** [davmac314/dinit#5]
Did you considered handling variables in service command?
Use case: running `confd` service inside docker container with `ETCD_HOST` variable provided by docker and `dinit` as PID 1.
```
type = process
command = /usr/bin/confd -interval 5 -node ${ETCD_HOST}
options = runs-on-console
```
Currently that has to be handled by `sh` script that is wrapping `confd` command.

**Comment by davmac314** [comment]
Yes, I think this is reasonable.

**Comment by davmac314** [comment]
An implementation of this has been committed to the master branch. It's necessary to set "load-options = sub-vars" in the service description to activate it. It hasn't been well tested yet and I may add some unit tests soon, but it seemed to work ok after a quick test.
