### ISSUE TITLE
[Feature request] status of service

### ISSUE THREAD

**Issue by Luciogi** [davmac314/dinit#50]
I would like to see status and small log of specific service using 
`dinitctl status service-name`
Using `dinitctl list` does show status , but it fill up whole screen.

**Comment by jackghg** [comment]
I was about to make the same request, the status command :)
with the status and maybe some more details.

**Comment by storp-co-in** [comment]
This should be there, dont know why it doesn't. Clearly not bloat.

**Comment by davmac314** [comment]
Implemented in v0.13.0 via "dinitctl status" subcommand. (The service log isn't displayed however and I don't intend to incorporate that functionality at present).
