### ISSUE TITLE
Integration tests will crash on version 0.15.0 or later!

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#62]
Hello.
I researched the strange breakdown of integration tests and came to an important conclusion!
I found that these bugs only exist in 0.15.0 or 0.15.1 and 0.14.0 has no problem with that!
"Why did I come to this conclusion?"
1- When integration tests in github actions are turned on, they are broken!
2- I tested this issue on drone.mobintestserver.ir. 0.14.0 has no problem with `make check-igr`. But 0.15.1 fails in `make check-igr‍`.
0.14.0: https://drone.mobintestserver.ir/Dinit_on_Devuan/dinit/42/1/2
0.15.1: https://drone.mobintestserver.ir/Dinit_on_Devuan/dinit/45

But there is a strange thing:
`make check-igr` on my computer does not fail with any of the dinit versions!

Really weird problem!

**Comment by davmac314** [comment]
The integration tests run fine for me on a Debian 10 VM. It must be something about the CI environment. Without a back trace or core dump there's not much I can do about it. You could also try bisecting to find which commit the problem starts happening at.

**Comment by mobin-2008** [comment]
I test integration tests commit by commit:
Note: The test is repeated twice
0.14.0 (4bd1e5e1af37540fdac66d394ef54b1c5ba4875c): Passed
0937819bcd2efabe3e7024d39d070e0c97b24a44: Passed

**Comment by davmac314** [comment]
I've tried myself, they start having problems with cdbdfec85433d5149c3885a73dfde86eb1bb9ad7

**Comment by davmac314** [comment]
I think that the latest push to master should resolve the problem.

**Comment by mobin-2008** [comment]
> I think that the latest push to master should resolve the problem.

Ok. i test this commit on my fork

**Comment by mobin-2008** [comment]
Debian-bullseye-amd64: Passed
Debian-bullseye-i386: Passed
Alpine-latest-aarch64: Passed
Alpine-latest-armv7: Passed
Alpine-latest-armv6: Passed

**Comment by mobin-2008** [comment]
I will create PR for this right now.
@davmac314 Do you really need a manual trigger?

**Comment by davmac314** [comment]
Ok, thanks!
Yes, manual trigger is very useful (for running CI for a branch).

**Comment by davmac314** [comment]
Merged, thanks!
