### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#65]
I know it's too early to do that. dinit is currently in version 0.15.1 and due to one of the design principles of dinit "Limited Feature Scope" it is very unlikely that we will encounter security vulnerabilities but again I think it is useful to consider a "Security policy" .
Just specify how to report a security vulnerability (github issues would definitely be a bad idea. I personally recommend email)

This is a marginal issue right now, but I personally think it will be important in the future.

regards

**Comment by AlexCr4ckPentest** [comment]
I agree with the comment above
anyway, this project needs audit, because in theory it may contains vulnerabilities

**Comment by davmac314** [comment]
I have added a document for now which asks that security issues be reported via email.

@AlexandrAlexeev7119 as this is open source anyone and everyone is free to audit the code for themselves.
