### ISSUE TITLE
How to load "Specifie" service from bootloader/kernel comand line?

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#69]
Hello.

 We can start the single service using dinit by entering `single` in the Bootloader command line.
But unfortunately, it is not possible to load another service with this method.
 This is important to me because I'm considering replacing the `single` service with `rescue` and also want to implement a systemd target-like structure in @Dinit-on-Devuan.
 This feature (calling any service using the Bootloader command line) makes it possible to run any target at system startup.

 @davmac314 Now my question is whether it is possible to do this or whether such a feature has been implemented or not?

regards

**Comment by davmac314** [comment]
It's not currently possible, but it would be a trivial feature to add. For supporting any generic target (service) there probably should be some command line flag (eg `--service rescue`), otherwise there is a risk that certain kernel parameters get leaked on to the init command line and are interpreted as a service name. Although possibly we could just ignore anything that doesn't name a service that we can find.

**Comment by mobin-2008** [comment]
> but it would be a trivial feature to add

I don't think so, but I agree there are more important issues.
> For supporting any generic target (service) there probably should be some command line flag (eg --service rescue), otherwise there is a risk that certain kernel parameters get leaked on to the init command line and are interpreted as a service name. Although possibly we could just ignore anything that doesn't name a service that we can find.

I think the `--service` argument solves the problem.
When the kernel does not understand a command from the bootloader, it sets it as an init argument.
When a specific service can only be loaded with the `--service` argument, the user must use `--service rescue` to start the `rescue` service, and the `rescue` keyword is not enough to load the `rescue` service.
One way to use this solution is to set the init argument in the bootloader as follows:
```
init="/sbin/init --service rescue"
```
It doesn't seem that simple but I think it can be made simpler.

Finally, if the requested service is not found, a warning will be displayed indicating that such a service does not exist and dinit will start normally.

**Comment by davmac314** [comment]
> One way to use this solution is to set the init argument in the bootloader as follows:

All you would need to do is add `--service rescue` to the kernel command line, I think. The kernel will pass that on to init. There's no need to specify `init=`.
