### ISSUE TITLE
Maybe typo in `dinit/src/includes/dinit-utmp.h`

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#72]
Hi.
This "if" doesn't seem right:
https://github.com/davmac314/dinit/blob/987999970a929addd3ba4a748df0ef4cb297006e/src/includes/dinit-utmp.h#L36-L40

`#define CLEAR UTMP_ON_BOOT 0 ` or `#define CLEAR_UTMP_ON_BOOT 0` ?

**Comment by davmac314** [comment]
Yes, fixed. Thanks.
