### ISSUE TITLE
Suggestions about comparison with InitNG

### ISSUE THREAD

**Issue by ismaell** [davmac314/dinit#77]
https://github.com/davmac314/dinit/blob/716fc4d57ba1b0a8340931dd3c951b8fe7b47480/doc/COMPARISON#L287-L294

- development ceased in February 2013.
- focused on Linux but portable, there used to be a port for Haiku.
- Website is dead.
- offers dependencies.

**Comment by davmac314** [comment]
Applied in 9758b643517a2fcc8a2aacba6e81d23cd665bff9, thanks.
