### ISSUE TITLE
Tweak documentation/comments about `-t`/`--service` in `dinit.cc`

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#87]
It needs to be revised:
https://github.com/davmac314/dinit/blob/a5a5e43b075ff97f419e85ffbbfbebebbad592ed/src/dinit.cc#L375-L396

Related: #69 & #76

**Comment by davmac314** [comment]
In the context of a command line argument not preceded by `-` and not handled by the processing for the other arguments, I think everything the comment says is correct.

**Comment by mobin-2008** [comment]
I don't remember what I wanted in the past, but seems like you right, we just might need to add `-t` to `long story short`.

**Comment by davmac314** [comment]
Hmm, but this comment is inside an `else` where `-t` has already been handled. I.e. the comment mostly applies to the `else` block, which is for processing arguments that do not begin with `-`. There's a direct correspondence between the "long story short" part and the code immediately following it, which won't be the case if it discusses the `-t` option . I think any comment about `-t should be where `-t` is handled (around line 325). But, I'm not sure such comment is needed.

**Comment by davmac314** [comment]
I'm going to close. If you really think a comment is needed (elsewhere) please raise a PR.
