### ISSUE TITLE
make fails with more than one job

### ISSUE THREAD

**Issue by jantatje** [davmac314/dinit#9]
`make -j` tries to build mconfig.h at the same time as other sourcefiles which require `mconfig.h`.

Adding
```
$(dinit_objects): includes/mconfig.h
```
and changing the dinit target to `dinit: $(dinit_objects)` in `src/makefile` fixes this problem for me.

`make check -j` also fails, but i did not look further into this.

**Comment by davmac314** [comment]
I'll look into this soon, thanks!

**Comment by davmac314** [comment]
Fixed. "make check -j" appears fine, make sure you check build instructions (either enable overcommit or disable santizers). Thanks!
