### ISSUE TITLE
dinit build successfully on linux-x86_64-musl and clang, but throw basic_string exception when running

### ISSUE THREAD

**Issue by Aleksanaa** [davmac314/dinit#99]
When I try to build dinit with musl and clang on linux, with either `CXXOPTS="-std=c++11 -fno-rtti"` or not, it can build without error and pass all checks. But running the dinit binary throws an error `libc++abi: terminating with uncaught exception of type std::length_error: basic_string`. Already tried with latest commit.

**Comment by mobin-2008** [comment]
You tried `make check` & `make check-igr`?

**Comment by Aleksanaa** [comment]
> Collaborator

I mistakenly used a path that was not cleared before rebuild with latest commit,and it has actually fixed. Sorry to bother.

by the way, hope you can publish a new release as soon as possible.

**Comment by davmac314** [comment]
Let's remove "wontfix" label because that implies there is a bug to fix :)

> by the way, hope you can publish a new release as soon as possible.

I'm hoping soon, but I need to find some time to spend working on a few issues.
